=== wengy12/CS466/TMA 1/part1/resume.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="https://www.w3schools.com" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- WE'll define basic types here -->
<xs:element name="name" type="xs:string"/>
<xs:element name="email" type="xs:string"/>
<xs:element name="github" type="xs:string"/>
<xs:element name="position" type="xs:string"/>
<xs:element name="company" type="xs:string"/>
<xs:element name="location" type="xs:string"/>
<xs:element name="time_period" type="xs:string"/>

<xs:element name="cventry">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="w3s:position" xmlns:w3s="https://www.w3schools.com"/>
            <xs:element ref="w3s:company" xmlns:w3s="https://www.w3schools.com"/>
            <xs:element ref="w3s:location" xmlns:w3s="https://www.w3schools.com"/>
            <xs:element ref="w3s:time_period" xmlns:w3s="https://www.w3schools.com"/>
            <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="general">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="w3s:name" xmlns:w3s="https://www.w3schools.com"/>
            <xs:element ref="w3s:email" xmlns:w3s="https://www.w3schools.com"/>
            <xs:element ref="w3s:github" xmlns:w3s="https://www.w3schools.com"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="skill">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="w3s:name" xmlns:w3s="https://www.w3schools.com"/>
            <xs:element name="list" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<!-- The actual type -->

<xs:element name="resume">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="w3s:general" xmlns:w3s="https://www.w3schools.com"/>
            <xs:element name="skills">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="w3s:skill" minOccurs="0" maxOccurs="unbounded" xmlns:w3s="https://www.w3schools.com"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="education">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="w3s:cventry" minOccurs="0" maxOccurs="unbounded" xmlns:w3s="https://www.w3schools.com"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="experience">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="w3s:cventry" minOccurs="0" maxOccurs="unbounded" xmlns:w3s="https://www.w3schools.com"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== wengy12/CS466/TMA 1/part1/resume.xml
<?xml version="1.0"?>
<resume
        xmlns="https://www.w3schools.com"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.w3schools.com/xml resume.xsd">

        <general>
            <name>Yunbing Weng</name>
            <email>wengyunbing@gmail.com</email>
            <github>https://github.com/wengy12/</github>
        </general>

        <skills>
            <skill>
                <name>Languages</name>
                <list>Russian (Native), Chinese(Native), English(Fluent)</list>
            </skill>
            <skill>
                <name>Programming Languages</name>
                <list>C++, Python, JS</list>
            </skill>
            <skill>
                <name>Tools</name>
                <list>Git, Latex, svn</list>
            </skill>
            <skill>
                <name>Personal</name>
                <list>Self-Motivated, Independent, Strong Work Ethic, Extremely fast learner, Event organization</list>
            </skill>
        </skills>

        <education>
            <cventry>
                <position>B.S. in Computer Science</position>
                <company>McMaster University</company>
                <location>Hamilton, Canada</location>
                <time_period>Sep. 2017 - PRESENT</time_period>
            </cventry>
            <cventry>
                <position>B.S. in Mathematics and Mechanics</position>
                <company>Moscow State University</company>
                <location>Moscow, Russia</location>
                <time_period>Sep. 2014 - Mar. 2016</time_period>
            </cventry>
        </education>

        <experience>
            <cventry>
                <position>Game Editor/Translation, Market research</position>
                <company>Luden.io</company>
                <location>Moscow, Russia</location>
                <time_period>May 2019 - Now</time_period>
                <description>Editor and translation for game "while True: learn()" based on Unity3D</description>
                <description>Market research and communication with Chinese partners</description>
            </cventry>
            <cventry>
                <position>Warehouse worker</position>
                <company>Amazon</company>
                <location>Milton, Ontario, Canada</location>
                <time_period>Sep 2017 - Nov 2017</time_period>
                <description>Warehouse packer.</description>
            </cventry>
        </experience>

</resume>
